baseurl = "/"
title = "APIDoc"

# Code higlighting settings
pygmentsCodefences = true
pygmentsCodeFencesGuesSsyntax = false
pygmentsOptions = ""
pygmentsStyle = "monokai"
# The monokai stylesheet is included in the base template.
pygmentsUseClasses = true



# Main menu

[[menu.main]]
    name = "Home"
    url  = "/"
    weight = 1


[params]
    search = true
    viewMorePostLink = "/post/"
    author = "ArcBlock"
    defaultKeywords = ["arcblock", "hugo", "go"]
    defaultDescription = "Site template made by arcblock using hugo"

    # Google Maps API key (if not set will default to not passing a key.)
    # googleMapsApiKey = ""

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "default"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    #
    # Enable the contact form by entering your Formspree.io email
    email = "contact@arcblock.io"

    support = "support@arcblock.io"
    copyright = "Copyright © 2018 ArcBlock Foundation Ltd."

    # Format dates with Go's time formatting
    date_format = "January 2"

    logo = "img/nav/logo.png"
    background = "img/hero/hero_building.jpg"
    gradient = "to top, rgba(132, 234, 209, 0.9), rgba(0, 149, 233, 0.9)"
    address = """<p><strong>Arcblock, Inc.</strong>
        <br>13/25 New Avenue
        <br>Newtown upon River
        <br>45Y 73J
        <br>England
        <br>
        <strong>Great Britain</strong>
      </p>
      """
    latitude = "-12.043333"
    longitude = "-77.028333"

 # Configure the language example tabs.

[[params.language_tabs]]
    key = "shell"
    name = "Shell"

[[params.language_tabs]]
    key = "go"
    name = "Go"

[[params.language_tabs]]
    key = "ruby"
    name = "Ruby"

[[params.language_tabs]]
    key = "python"
    name = "Python"

[Permalinks]
    post = "/post/:year/:month/:day/:filename/"

[params.widgets]
    categories = true
    tags = true
    search = false


